### ISSUE TITLE
playing in the sandbox with terraform 

### ISSUE THREAD

**Issue by ghost** [jamiemccrindle/aws-access#2]
I found your tool when Corey Quinn linked to it in his newsletter last week in aws.  

Great idea, brilliant execution.

I'm considering putting into play, with my team.  But now I'm thinking more deeply about how it will play with terraform.  As you may know terraform doesn't like things created out-of-band.  

So an associated cleanup script would probably be necessary.  And wondering about tagging through resource changes, so they're easy to find and sweep up, if/when terraform needs to destroy a security group.

Then again I was also thinking of a script that generates terraform code to do that same magic that your script does.

Anyway, just thinking out loud here.  Good stuff, thanks for the inspiration.  🥇

**Comment by jamiemccrindle** [comment]
Thanks for the kind words Sean. Glad you like it.

Great point about terraform.

**Comment by tdmalone** [comment]
I haven’t used aws-access but I implemented a similar idea with a Lambda function. The way I dealt with it in Terraform was keeping the special SG always there and attached to my instances, but not managing that specific SG through Terraform.

Terraform is happy to see it’s still attached, but doesn’t care what rules are in it.

**Comment by ghost** [comment]
Thx Tim that's a good idea.

Certainly can use an ARN to reference a SG created out-of-band.

**Comment by tdmalone** [comment]
I don’t think you even need an ARN - just the SG name. As an aside, if you ever are referencing ARNs for an outside resource, try setting up a data resource, will save you pain if things change.

**Comment by jamiemccrindle** [comment]
Closing this for now as I think that there may need to be a different mechanism for terraform. Thanks for your thoughts / suggestions etc.!
